### ISSUE TITLE
Complete the "Qt Crash Course" Section in Documentation

### ISSUE THREAD

**Issue by mohass98** [mohass98/pyqtgraph#1]
### Short description
The Documentation "Qt Crash Course" currently lacks several crucial components, leaving it incomplete and potentially confusing for newcomers. To make this section more comprehensive and helpful, I suggest adding detailed explanations and examples on the following topics:

### Mouse and Keyboard Input:

- Explanation and examples of handling mouse and keyboard events in PyQt applications.
- How to capture and respond to user inputs using PyQtGraph widgets.
- Best practices for implementing interactive features like zoom, pan, and click events.

### QTimer and Multi-Threading:
- Introduction to QTimer and its usage for periodic updates in GUI applications.
- Detailed guide on implementing multi-threading in PyQt applications to maintain UI responsiveness.
- Practical examples demonstrating the use of QTimer and multi-threading with PyQtGraph.

### Multi-Threading vs. Multi-Processing in Qt:
- Clear explanation of the differences between multi-threading and multi-processing.
- Discussion on when to use multi-threading versus multi-processing in the context of Qt applications.
- Examples illustrating the implementation of both approaches in PyQtGraph.

### Suggested Improvements:
- Expand the existing sections: Provide more detailed explanations of PyQt basics, including widgets, layouts, and the main event loop.
- Integrate practical examples: Demonstrate the integration of PyQt with PyQtGraph through comprehensive examples.
- Include user interaction handling: Elaborate on how to effectively manage mouse and keyboard input in applications using PyQtGraph.
- Cover advanced topics: Provide in-depth guides on using QTimer, multi-threading, and multi-processing to enhance application performance and responsiveness.

**Comment by Lamis-Abla** [comment]
hey @kadheer here are still two open topics, would you like to write something here ? Mouse and Keyboard Input I have made ready 7a3db8dd731119488a05a2d67f916c8352bda30a, QTimer and Multi-Threading I will still make. the topic Multi-Threading vs. Multi-Processing in Qt you can edit

**Comment by kadheer** [comment]
Sicherlich! Ich werde das machen. Das Thema Multi-Threading vs. Multi-Processing werde ich alles heute machen.

**Comment by mohass98** [comment]
Closed this feature as it is implemented into the documents.
