### ISSUE TITLE
Add option to swap X and Y axes via context menu

### ISSUE THREAD

**Issue by mohass98** [mohass98/pyqtgraph#3]
### Description:
Referencing to Issue #515
Currently, PyQtGraph provides a variety of interactive features through its context menu for manipulating plots. However, there is no built-in option to swap the X and Y axes directly from the context menu. This feature would be useful for users who need to interchange the axes of their plots for better visualization or analysis purposes.

### Proposed Feature:

- Add a menu item in the context menu of plots (right-click menu) that allows users to swap the X and Y axes.
- Upon selection, the plot should exchange the current X axis data with the Y axis data and vice versa, updating the plot accordingly.

### Benefits:

- Enhances the flexibility and usability of PyQtGraph by providing a commonly requested feature.
- Reduces the need for users to manually manipulate data arrays or recreate plots when they want to view data along different dimensions.

**Comment by Silas-K** [comment]
### First approach for this Issue commited in 1ccc2b5

Affected areas: [ViewBoxMenu.py](https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/graphicsItems/ViewBox/ViewBoxMenu.py) and [ViewBox.py](https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/graphicsItems/ViewBox/ViewBox.py)

#### `ViewBoxMenu`:
1. Added a new action to the ViewBoxMenu to choose "Swap X and Y Axes"
```python
        self.swapAxesAction = QtGui.QAction(
            translate("ViewBox", "Swap X and Y Axes"), self
        )
        self.swapAxesAction.setCheckable(True)
        self.swapAxesAction.triggered.connect(self.swapAxesToggled)
        self.addAction(self.swapAxesAction)

```

2. Added the method/slot to `ViewBoxMenu` that triggers the `swapAxes` method in `ViewBox`
```python
    def swapAxesToggled(self):
        print('Switch Axes was clicked')
        self.view().swapAxes()

```
#### `ViewBox`:
3. Added a variable to the state to track whether x and y axis are swapped:
```python
        self.state = {
            #...
            'xyAxesSwapped': False,
            #...

```
3. Created the `swapAxes` method, which swaps the state values for the axes
```python
    def swapAxes(self):
        print('Switch Axes was received')
        state = self.getState()

        # Swap x and y axis ranges
        x_range = state['targetRange'][0]
        y_range = state['targetRange'][1]
        self.setRange(yRange=x_range, padding=0)
        self.setRange(xRange=y_range, padding=0)

        self.enableAutoRange(ViewBox.XAxis, state['autoRange'][1])
        self.enableAutoRange(ViewBox.YAxis, state['autoRange'][0])

        self.setMouseEnabled(x=state['mouseEnabled'][1], y=state['mouseEnabled'][0])
        self.invertX(state['yInverted'])
        self.invertY(state['xInverted'])

        # Track axis swapping
        self.state['xyAxesSwapped'] = not self.state[
            'xyAxesSwapped'
        ]

        # Update
        self._matrixNeedsUpdate = True  # updateViewRange won't detect this for us
        self.updateViewRange()
        self.update()
        self.sigStateChanged.emit(self)
        self.sigYRangeChanged.emit(self, tuple(self.state['viewRange'][1]))
        self.sigXRangeChanged.emit(self, tuple(self.state['viewRange'][0]))

```

4. Updated the `updateMatrix` method to invert the x-axis and then perform a +90 degree rotation, when axes are swapped
```python
        if self.state["xyAxesSwapped"]:
            # Adjust the transformation for swapped axes
            self.invertX()
            m.rotate(90)  # Rotate the matrix by 90 degrees

```

### Current challenges with the Logic

- Mouse Interaction: Mouse interaction is not correctly considering the axis swap, leading to incorrect behavior.
- Inverted X-axis Values: X-axis values are now inverted (from positive to negative), which is incorrect.
- Handling all possible combinations of `yInverted`, `xInverted`, and `xyAxesSwapped` (the new variable) configurations requires careful consideration. The specific areas in need of adjustment beyond `updateMatrix` and `swapAxes` are yet to be fully identified.

> [!NOTE]
> Could a different approach be more effective?

**Comment by mohass98** [comment]
Hey @Silas-K, I had a similar approach to yours.

I implemented the first three steps in the same way. However, I customised the update_matrix slightly differently. I commited this in 9a2a0c6, the ViewBoxMenu in 02f1d8b.

```python
def updateMatrix(self, changed=None):
        if not self._matrixNeedsUpdate:
            return

        bounds = self.rect()
        vr = self.viewRect()
        if vr.height() == 0 or vr.width() == 0:
            return

        m = QtGui.QTransform()
        center = bounds.center()
        m.translate(center.x(), center.y())

        if self.state['xyAxesSwapped']:
            #scale = Point(bounds.height() / vr.width(), bounds.width() / vr.height())

            m.scale()
            st = Point(vr.center())
            m.translate(-st[1], -st[0])

        if not self.state['xyAxesSwapped']:
            scale = Point(bounds.width() / vr.width(), bounds.height() / vr.height())

            #Consider inversion
            if not self.state['yInverted']:
                scale = scale * Point(1, -1)
            if self.state['xInverted']:
                scale = scale * Point(-1, 1)

            m.scale(scale[0], scale[1])
            st = Point(vr.center())
            m.translate(-st[0], -st[1])

        self.childGroup.setTransform(m)
        self._matrixNeedsUpdate = False

        self.sigTransformChanged.emit(self)
```

### Current challenges with the Logic

If I try to swap the axles, this works. However, I have the problem that the graph then disappears. If I then swap the axes again, the logic is completely confused.

Perhaps we can combine our approaches to find the solution.
![xyaxes1](https://github.com/mohass98/pyqtgraph/assets/153856978/d157c6ec-026c-4de9-ad71-fe682c62185e)
![xyaxes2](https://github.com/mohass98/pyqtgraph/assets/153856978/34feb24e-5feb-45de-8c1b-cac6ad2e331f)

**Comment by mohass98** [comment]
After communication between @Silas-K Silas-K and myself, it was decided that the changes were too far-reaching, as the changes to the axes have too many dependencies in the library. The data can also be easily manipulated programmatically, causing the axes to be swapped. As a result, it was decided that this feature would not be pursued further. The issue is therefore closed.

**Comment by mohass98** [comment]
After communication between @Silas-K Silas-K and myself, it was decided that the changes were too far-reaching, as the changes to the axes have too many dependencies in the library. The data can also be easily manipulated programmatically, causing the axes to be swapped. As a result, it was decided that this feature would not be pursued further. The issue is therefore closed.
